# Travis CI script

language: c

env:
- BUILD_TYPE=default ZMQ_REPO=zeromq2-x
- BUILD_TYPE=default ZMQ_REPO=zeromq3-x
- BUILD_TYPE=default ZMQ_REPO=zeromq4-x WITH_LIBSODIUM=1
- BUILD_TYPE=default ZMQ_REPO=libzmq    WITH_LIBSODIUM=1
- BUILD_TYPE=qt-android
- BUILD_TYPE=check-py
- BUILD_TYPE=cmake

# ZMQ stress tests need more open socket (files) than the usual default
before_script:
- sudo apt-get install uuid-dev
- ulimit -n 64000
- ./autogen.sh

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
