version: build-{build}

clone_depth: 1 #clone entire repository history if not defined

#do not build on tags
skip_tags: true

os: Visual Studio 2015 #  Windows Server 2012

environment:
  CMAKE_GENERATOR: "Visual Studio 14 2015"

matrix:
  fast_finish: false #finish build once one of the jobs fails

platform:
  - Win32
  - x64

configuration:
  - Release
  - Debug

#scripts that are called at very beginning, before repo cloning
init:
  #Put this line somewhere when you want to debug something using rdp
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- set #debug: view all environment variables
  - ps: Update-AppveyorBuild -Version "git-$($env:appveyor_repo_commit.substring(0,8))"
  - cmake --version
  - msbuild /version
  - cmd: reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
  #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  #- cmake --help #debug: view available generators

#scripts that run after cloning repository
install:
  # Build the dependency (libzmq)
  - cmd: if "%Platform%"=="x64" set "CMAKE_GENERATOR=%CMAKE_GENERATOR% Win64"
  - cmd: echo "Generator='%CMAKE_GENERATOR%'"
  - cmd: echo "Platform='%Platform%'"
  - cmd: cd C:\projects
  - cmd: git clone https://github.com/zeromq/libzmq.git --depth 1
  - cmd: set LIBZMQ_BUILDDIR=C:\projects\build_libzmq\%Platform%\%Configuration%
  - cmd: md "%LIBZMQ_BUILDDIR%"
  - cmd: cd "%LIBZMQ_BUILDDIR%"
  - ps: $blockRdp = $true;
  - cmd: cmake -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" -G "%CMAKE_GENERATOR%" C:\projects\libzmq
  - cmd: msbuild /v:minimal /maxcpucount:%NUMBER_OF_PROCESSORS% /p:Configuration=%Configuration% libzmq.vcxproj #zeromq.sln
  - cmd: set ZEROMQ_INCLUDE_DIRS="C:\projects\libzmq\include"
  - cmd: set ZEROMQ_LIBRARY_DIRS="%LIBZMQ_BUILDDIR%\lib\%Configuration%"
  - cmd: move "%ZEROMQ_LIBRARY_DIRS%\libzmq-*lib" "%ZEROMQ_LIBRARY_DIRS%\zmq.lib"
  - cmd: cd %APPVEYOR_BUILD_FOLDER%

#where to clone the git repository to
clone_folder: C:\projects\czmq

#scripts to run before build
before_build:
  - cmd: set CZMQ_BUILDDIR=C:\projects\build_czmq
  - cmd: md "%CZMQ_BUILDDIR%"
  - cd "%CZMQ_BUILDDIR%"
  - cmd: cmake -G "%CMAKE_GENERATOR%" -D PC_ZEROMQ_INCLUDE_DIRS="%ZEROMQ_INCLUDE_DIRS%" -D PC_ZEROMQ_LIBRARY_DIRS="%ZEROMQ_LIBRARY_DIRS%" -D CMAKE_CXX_FLAGS_RELEASE="/MT" -D CMAKE_CXX_FLAGS_DEBUG="/MTd" "%APPVEYOR_BUILD_FOLDER%" 

build:
  parallel: true
  project: C:\projects\build_czmq\czmq.sln
  verbosity: minimal #quiet|minimal|normal|detailed

#scripts to run after build
after_build:
  # Pack the artifacts
  - cmd: cd "%CZMQ_BUILDDIR%\%Configuration%"
  - cmd: copy "%LIBZMQ_BUILDDIR%\bin\%Configuration%\libzmq-*dll" .
  - cmd: 7z a -y -bd -mx=9 czmq.zip czmq_selftest.exe czmq.dll libzmq-*.dll
  - ps: Push-AppveyorArtifact "czmq.zip" -Filename "czmq-${env:Platform}-${env:Configuration}.zip"
  - cmd: czmq_selftest # -v

test:
  none
